data:
  data_dir: [/workspace/768]
  image_size: 512
# training setting
train:
  num_workers: 1
  seed: 42
  train_batch_size: 15
  num_epochs: 1
  gradient_accumulation_steps: 1
  grad_checkpointing: true
  gradient_clip: 0.1
  optimizer:
    lr: 1.0e-4
    type: AdafactorWrapper
    scale_parameter: false
    relative_step: false
    warmup_init: false
#  optimizer:
#    lr: 6.0e-5
#    type: AdafactorFusedWrapper
#    scale_parameter: false
#    relative_step: false
#    warmup_init: false
#  optimizer:
#    lr: 1.0e-4
#    type: AdamW
#    weight_decay: 0.01
#    eps: 1.0e-8
#    betas: [0.9, 0.999]
  lr_schedule: constant
  lr_schedule_args:
    num_warmup_steps: 0
  local_save_vis: false # if save log image locally
  visualize: true
  eval_sampling_steps: 1200
  log_interval: 30
  save_model_epochs: 1
  save_model_steps: 1200
  work_dir: output
  online_metric: false
  eval_metric_step: 200000
  online_metric_dir: metric_helper
  validation_prompts:
    - 1girl, solo, animal ears, bow, teeth, jacket, tail, open mouth, brown hair, orange background, bowtie, orange nails, simple background, cat ears, orange eyes, blue bow, animal ear fluff, cat tail, looking at viewer, upper body, shirt, school uniform, hood, striped bow, striped, white shirt, black jacket, blue bowtie, fingernails, long sleeves, cat girl, bangs, fangs, collared shirt, striped bowtie, short hair, tongue, hoodie, sharp teeth, facial mark, claw pose
    - woman, solo, black hair, medium length hair, female focus, solo, bedroom, messy room, standing, black tube top, black panties, camel toe , peace sign, choker, top pulled down, taking a selfie
    - A lively scene unfolds on a ship at night. a group of people, both boys and girls, are gathered around a large fire pit. they are all smiling and appear to be in high spirits, with some of them holding up their arms in celebration. the ship is adorned with colorful lanterns that hang from the rigging, casting a warm glow over the scene. the sky above is dark, suggesting its nighttime, and the ship is set against this backdrop. the atmosphere is one of joy and camaraderie, as if they are celebrating a victory or a special occasion.
    - молодая девушка в красном платье
    - собака, бостон терьер
    - нарядная новогодняя елка, красивые игрушки, звезда сверху, огоньки, на тёмном фоне
# model config
model:
  model: SanaMS_1600M_P1_D20
  image_size: 512
  aspect_ratio_type: ASPECT_RATIO_512
  mixed_precision: bf16
  fp32_attention: true
  load_from: 
  resume_from:
  multi_scale: true
  attn_type: linear
  linear_head_dim: 32
  ffn_type: glumbconv
  mlp_acts:
    - silu
    - silu
    - null
  mlp_ratio: 2.5
  use_pe: false
  qk_norm: false
  class_dropout_prob: 0.1
# VAE setting
vae:
  vae_type: sd3
  vae_pretrained: AuraDiffusion/16ch-vae
  scale_factor: 0.18215
  vae_latent_dim: 16
  vae_downsample_rate: 8
  sample_posterior: true
# text encoder
text_encoder:
  text_encoder_name: mexma-siglip
  y_norm: true
  y_norm_scale_factor: 0.01
  model_max_length: 512
# Sana schedule Flow
scheduler:
  predict_v: true
  noise_schedule: linear_flow
  pred_sigma: false
  flow_shift: 1.0
  # logit-normal timestep
  weighting_scheme: logit_normal
  logit_mean: 0.0
  logit_std: 1.0
  vis_sampler: flow_euler
